version: '3.7'

services:

  flask:
    build: 
      context: flask
    restart: always
    ports:
      - "8080"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    depends_on:
      - flask
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
