version: '3.7'

services:

  flask:
    build: ./flask
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
    ports:
      - "8080"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    depends_on:
      - flask
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
