version: '3'

services:

  flask:
    build: 
      context: flask
    ports:
      - "8080"

  nginx:
    build: 
      context: nginx
    container_name: nginx
    restart: always
    depends_on:
      - flask
    ports:
      - "80:80"
